name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    # 屏幕适配
  flutter_screenutil: ^5.8.4
    # 提示 toast
  fluttertoast: ^8.2.4
   # 通讯
  dio: ^5.4.0 
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
   # 获取设备信息
  device_info_plus: ^9.1.1
  image_picker: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - static/images/
    - assets/images/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
          weight: 400 # normal
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
